language: python
python:
  - "2.7"
  - "3.7"

install:
    - python setup.py install

script:
    - export TARGET="-m hfcommon_tests.runtests"
    - python -bb $TARGET
    - python -O $TARGET
    - LANG=C python $TARGET
    - LANG=en_US.utf-8 python $TARGET
